server:
  port: 8080

spring:
  application:
    name: store


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
